;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.export		_main

.segment	"RODATA"

L000F:
	.byte	$44,$4F,$4E,$45,$0A,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$00
	lda     #$64
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	jsr     decsp2
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
L0004:	ldy     #$01
	jsr     ldaxysp
	cmp     #$10
	txa
	sbc     #$27
	bvc     L000B
	eor     #$80
L000B:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0007
	jmp     L0005
L0007:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     tosaddax
	jsr     pushax
	jsr     incsp2
	ldy     #$01
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$00
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L0004
L0005:	lda     #<(L000F)
	ldx     #>(L000F)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	jsr     incsp6
	rts

.endproc

