;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.export		_main

.segment	"RODATA"

L001A:
	.byte	$C4,$CF,$CE,$C5,$20,$C9,$CE,$20,$25,$44,$20,$CA,$C9,$C6,$C6,$D9
	.byte	$0D,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     $00A1
	lda     #$00
	clc
	adc     $00A2
	bcc     L001E
	inx
L001E:	jsr     pushax
	lda     #$64
	jsr     pusha0
	lda     #$01
	jsr     pusha0
	jsr     decsp4
	lda     #$00
L0022:	ldy     #$02
	jsr     staxysp
	cmp     #$10
	txa
	sbc     #$27
	bvc     L0010
	eor     #$80
L0010:	bpl     L0020
	ldy     #$05
	jsr     ldaxysp
	clc
	ldy     #$06
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	jsr     incsp2
	ldy     #$03
	jsr     ldaxysp
	jsr     incax1
	jmp     L0022
L0020:	ldx     $00A1
	lda     #$00
	clc
	adc     $00A2
	bcc     L001F
	inx
L001F:	jsr     stax0sp
	lda     #<(L001A)
	ldx     #>(L001A)
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	sec
	ldy     #$0A
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$04
	jsr     _printf
	ldx     #$00
	txa
	ldy     #$0A
	jmp     addysp

.endproc

