;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.export		_main

.segment	"RODATA"

L001A:
	.byte	$44,$4F,$4E,$45,$20,$49,$4E,$20,$25,$64,$20,$4A,$49,$46,$46,$59
	.byte	$0A,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$00
	lda     $00A1
	tax
	lda     #$00
	jsr     pushax
	ldx     #$00
	lda     $00A2
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$64
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	jsr     decsp4
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
L0009:	ldy     #$03
	jsr     ldaxysp
	cmp     #$10
	txa
	sbc     #$27
	bvc     L0010
	eor     #$80
L0010:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L000C
	jmp     L000A
L000C:	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosaddax
	jsr     pushax
	jsr     incsp2
	ldy     #$03
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$02
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L0009
L000A:	ldx     #$00
	lda     $00A1
	tax
	lda     #$00
	jsr     pushax
	ldx     #$00
	lda     $00A2
	jsr     tosaddax
	ldy     #$00
	jsr     staxysp
	lda     #<(L001A)
	ldx     #>(L001A)
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     tossubax
	jsr     pushax
	ldy     #$04
	jsr     _printf
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	ldy     #$0A
	jsr     addysp
	rts

.endproc

