;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.export		_start_sid_asm
	.export		_start_sid_c
	.export		_rand_byte
	.export		_rand_word
	.export		_main

.segment	"RODATA"

L0039:
	.byte	$0D,$D2,$C1,$CE,$C4,$CF,$CD,$20,$D7,$CF,$D2,$C4,$D3,$3A,$0D,$00
L0029:
	.byte	$D2,$C1,$CE,$C4,$CF,$CD,$20,$C2,$D9,$D4,$C5,$D3,$3A,$0D,$00
L0045:
	.byte	$25,$44,$20,$00
L0035	:=	L0045+0

; ---------------------------------------------------------------
; void __near__ start_sid_asm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_start_sid_asm: near

.segment	"CODE"

	lda     #$ff
	sta     $d40e
	sta     $d40f
	lda     #$80
	sta     $d412
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ start_sid_c (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_start_sid_c: near

.segment	"CODE"

	lda     #$FF
	sta     $D40E
	sta     $D40F
	lda     #$80
	sta     $D412
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ rand_byte (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rand_byte: near

.segment	"CODE"

	ldx     #$00
	lda     $D41B
	rts

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ rand_word (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rand_word: near

.segment	"CODE"

	jsr     decsp2
L001E:	jsr     _rand_byte
	tax
	lda     #$00
	jsr     pushax
	jsr     _rand_byte
	jsr     tosora0
	jsr     stax0sp
	cmp     #$00
	txa
	sbc     #$80
	bcs     L001E
	jsr     ldax0sp
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp2
	jsr     _start_sid_c
	lda     #<(L0029)
	ldx     #>(L0029)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	txa
L004D:	jsr     stax0sp
	cmp     #$14
	txa
	sbc     #$00
	bvc     L0032
	eor     #$80
L0032:	bpl     L002C
	lda     #<(L0035)
	ldx     #>(L0035)
	jsr     pushax
	jsr     _rand_byte
	jsr     pushax
	ldy     #$04
	jsr     _printf
	jsr     ldax0sp
	jsr     incax1
	jmp     L004D
L002C:	lda     #<(L0039)
	ldx     #>(L0039)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	txa
L004E:	jsr     stax0sp
	cmp     #$14
	txa
	sbc     #$00
	bvc     L0042
	eor     #$80
L0042:	asl     a
	lda     #$00
	tax
	bcc     L004A
	lda     #<(L0045)
	ldx     #>(L0045)
	jsr     pushax
	jsr     _rand_word
	jsr     pushax
	ldy     #$04
	jsr     _printf
	jsr     ldax0sp
	jsr     incax1
	jmp     L004E
L004A:	jmp     incsp2

.endproc

